<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_929 ratings</name>
   <tag></tag>
   <elementGuidId>c0a83679-5aac-4611-a964-8e06bbabea55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acrCustomerReviewText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='acrCustomerReviewText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c514eb0a-27b9-4e4b-8ccc-0325085abd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acrCustomerReviewText</value>
      <webElementGuid>4dc70268-4df9-4be4-8e8f-4a5bc4e55732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-base</value>
      <webElementGuid>400ec966-8f9f-407c-8b4c-1eea41f94176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>929 ratings</value>
      <webElementGuid>874b805a-bf4a-4b93-a0d8-70aa76a9eccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;averageCustomerReviews_feature_div&quot;)/div[@id=&quot;averageCustomerReviews&quot;]/span[@class=&quot;a-declarative&quot;]/a[@id=&quot;acrCustomerReviewLink&quot;]/span[@id=&quot;acrCustomerReviewText&quot;]</value>
      <webElementGuid>9f9223d4-32e1-4f7b-9d86-8304963ee1d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='acrCustomerReviewText']</value>
      <webElementGuid>d1a1ce1b-cfbf-421f-8459-f6ec5524ea5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='acrCustomerReviewLink']/span</value>
      <webElementGuid>e36edc44-92a8-44e6-b816-ed444d4b0959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/a/span</value>
      <webElementGuid>acd77103-ea0a-425b-a4ae-aacd63a05add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'acrCustomerReviewText' and (text() = '929 ratings' or . = '929 ratings')]</value>
      <webElementGuid>c56e3b2e-8d5a-46a7-a2d5-55c5df6403c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
