<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All</name>
   <tag></tag>
   <elementGuidId>a4a38308-c682-40f4-b67d-c3de8fe2e64e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-hamburger-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-hamburger-menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90aa0bc4-0efd-4eed-baa9-302e67f1f553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript: void(0)</value>
      <webElementGuid>cc8ebb80-0579-40c3-87f0-8e5e3f557884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-hamburger-menu</value>
      <webElementGuid>9fe038c6-4f7a-4b9c-afbe-2cc17e3a8394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ef7f68b9-f8ae-42e1-999d-8915e1db7cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open Menu</value>
      <webElementGuid>007f41fa-4ace-48c1-85de-e6fc877552a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>8a2e18a8-8997-494f-8f55-8f84c612a591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>HamburgerMenuDesktop</value>
      <webElementGuid>41bb9f6b-d92c-41ee-95c6-483766723efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>177bfba9-853b-473a-94d6-ec5ae9969127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>qzzv5x-7g6fmw-9fc6il-misjsb</value>
      <webElementGuid>fcb4b596-d7e8-45a6-8367-676344d98754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    
    All
  </value>
      <webElementGuid>5a8c2005-58ac-45a0-9e90-c94e6b3850a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-hamburger-menu&quot;)</value>
      <webElementGuid>8ae094bd-0951-46dc-a3b6-48b01b85fd3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-hamburger-menu']</value>
      <webElementGuid>b2438590-0319-4bbf-a750-06581ddb45f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-main']/div/a</value>
      <webElementGuid>4aa0289a-829a-4c08-b24c-018389d1ae7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript: void(0)')]</value>
      <webElementGuid>4d16a384-845e-4505-9623-391bee04fcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/a</value>
      <webElementGuid>7eb3ed9d-705f-4e68-a9d7-8bf5433b21f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript: void(0)' and @id = 'nav-hamburger-menu' and (text() = '
    
    All
  ' or . = '
    
    All
  ')]</value>
      <webElementGuid>564e0950-97a8-4c90-bacd-a82a962cb491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
