<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_sc-product-image</name>
   <tag></tag>
   <elementGuidId>163c0a6a-9129-4d3e-97a6-4c928eb181ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sc-product-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sc-active-d4ac1fa0-e703-4385-ac3e-6da7dc7ea00c']/div[4]/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7aab43d8-f5c6-44fc-aac5-320dd28dfa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/61LI8DI2XEL._AC_AA180_.jpg</value>
      <webElementGuid>082fb6dc-0c00-4e16-b441-f9e94ee05ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sony Alpha a7 III 24.2MP Full Frame Mirrorless Digital Interchangeable-Lens Camera - Bundle with Sony FE 24-105mm f/4 G OSS Standard Zoom E-Mount Lens, Opens in a new tab</value>
      <webElementGuid>05e98289-2a09-41af-909f-74c945a61d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>180</value>
      <webElementGuid>b9d7b396-6e07-45a5-9a7b-596196818e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>180</value>
      <webElementGuid>25102027-b9dc-407f-bb28-f3acd9b2491e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-product-image</value>
      <webElementGuid>4d759eb2-62e8-4560-8a7a-b66f4310007b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/61LI8DI2XEL._AC_AA180_.jpg 1x, https://m.media-amazon.com/images/I/61LI8DI2XEL._AC_AA360_.jpg 2x, https://m.media-amazon.com/images/I/61LI8DI2XEL._AC_AA540_.jpg 3x, https://m.media-amazon.com/images/I/61LI8DI2XEL._AC_AA720_.jpg 4x</value>
      <webElementGuid>e87e17eb-4ad5-463f-90c1-84d7c70ee61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-d4ac1fa0-e703-4385-ac3e-6da7dc7ea00c&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-grid-vertical-align a-grid-top sc-list-item-content-inner&quot;]/div[@class=&quot;a-spacing-mini sc-item-content-group&quot;]/a[@class=&quot;a-link-normal sc-product-link&quot;]/img[@class=&quot;sc-product-image&quot;]</value>
      <webElementGuid>b5ac6a8a-2484-48a2-a3a2-74c3fa714b44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-d4ac1fa0-e703-4385-ac3e-6da7dc7ea00c']/div[4]/div/div[2]/a/img</value>
      <webElementGuid>bdae0ad2-30eb-4b37-8b07-acf8e312eda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sony Alpha a7 III 24.2MP Full Frame Mirrorless Digital Interchangeable-Lens Camera - Bundle with Sony FE 24-105mm f/4 G OSS Standard Zoom E-Mount Lens, Opens in a new tab']</value>
      <webElementGuid>79838c97-deb8-4003-bbc0-6cb8053cb568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>9f37f95c-789a-4f68-b589-df34ee095c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/I/61LI8DI2XEL._AC_AA180_.jpg' and @alt = 'Sony Alpha a7 III 24.2MP Full Frame Mirrorless Digital Interchangeable-Lens Camera - Bundle with Sony FE 24-105mm f/4 G OSS Standard Zoom E-Mount Lens, Opens in a new tab']</value>
      <webElementGuid>08dda41c-f9c3-46b4-b33b-0b79b2d1cfe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
