<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Cart</name>
   <tag></tag>
   <elementGuidId>ce96e3ec-c7ff-463f-87ed-f725cae69b0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-3-announce</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='a-autoid-3-announce']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4baf0da0-7e6f-46c1-b8f0-16f0dde65085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text</value>
      <webElementGuid>67c66fee-4b3f-4e02-883d-fbc75dfc90da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0dad2a41-8a23-498c-95d2-1b111379135e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-autoid-3-announce</value>
      <webElementGuid>69b54c0f-56fa-4a3c-80ba-bb8a6fcba4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>5c43ebc1-aed3-40eb-af39-c81d7683fcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-3-announce&quot;)</value>
      <webElementGuid>f98431d1-3f9c-4b72-8a8d-9ed1c6aaa5ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='a-autoid-3-announce']</value>
      <webElementGuid>6e8be046-d074-4a3f-8515-25fd6a4320d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-3']/span/button</value>
      <webElementGuid>b7d633d1-28e6-4071-aba9-20477cca3088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/span/div/div/form/span/div/div/span/span/button</value>
      <webElementGuid>357f871e-1cdd-41f4-8bff-a88fef4cc04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'a-autoid-3-announce' and (text() = 'Add to Cart' or . = 'Add to Cart')]</value>
      <webElementGuid>f9ec728e-b0c4-4fe0-b346-5e3f441846fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
